# Generated by Django 4.2.6 on 2023-10-31 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_cars_yearcar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='Clients',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='yearCar',
            new_name='year',
        ),
    ]
