# Generated by Django 4.2.6 on 2023-10-31 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_cars_car_rename_clients_client_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Cars',
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
