# Generated by Django 4.2.6 on 2023-10-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_rename_car_cars_rename_client_clients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='client',
            new_name='clients',
        ),
    ]
